# Enable CORS for all files so they can be loaded from other domains
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Cache-Control = "public, max-age=31536000, immutable"

# Specific caching for versioned assets
[[headers]]
  for = "/v*/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Build settings (if needed)
[build]
  publish = "."